name: Google Cloud Auto Inventory

on:
    workflow_dispatch:

jobs:
    gcp-scan:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        env: 
         CI_COMMIT_MESSAGE: Fetched GCP Assets

        steps:
        # Step 1: Checkout the repository
        - name: Checkout Code
          uses: actions/checkout@v3

        # Step 2: Configure GCP credentials
        - name: Configure GCP Credentials
          uses: google-github-actions/auth@v1
          with:
            credentials_json: ${{ secrets.GCP_CREDENTIALS }}

        # Step 3: Debug GCP Authentication (Optional)
        - name: Debug GCP Authentication
          run: gcloud auth list

        # Step 4: Set up Python
        - name: Set up Python 3.x
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'

        # Step 5: Install System Dependencies
        - name: Install System Dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y python3-dev libatlas-base-dev gfortran libopenblas-dev liblapack-dev build-essential

        # Step 6: Install Python Dependencies
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install --only-binary=:all: numpy==1.24.4 pandas==2.1.0 google-cloud-resource-manager==1.10.1 openpyxl==3.1.2

        # Step 7: Run GCP Auto Inventory
        - name: Run GCP Auto Inventory
          run: |
            python3 scan.py -s config/gcp.json
            echo "${{ env.CI_COMMIT_MESSAGE }}"

        # Step 8: Commit and Push Results
        - name: Commit and Push Results
          run: |
            git config --local user.name "GitHub Actions"
            git config --local user.email "actions@github.com"
            mkdir -p data/json/gcp
            git add data/json/gcp
            git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
            git push origin HEAD:${{ github.ref }}

    process-inventory:
        needs: gcp-scan
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        env: 
         CI_COMMIT_MESSAGE: Processed GCP Inventory

        steps:
            # Step 1: Checkout the repository
            - name: Checkout Code
              uses: actions/checkout@v3

            # Step 2: Set up Python
            - name: Set up Python 3.x
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            # Step 3: Install System Dependencies
            - name: Install System Dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y python3-dev libatlas-base-dev gfortran libopenblas-dev liblapack-dev build-essential

            # Step 4: Install Python Dependencies
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install --only-binary=:all: numpy==1.24.4 pandas==2.1.0 openpyxl==3.1.2

            # Step 5: Run Inventory Processing
            - name: Run Inventory Processing
              run: |
                python3 main.py
                echo "${{ env.CI_COMMIT_MESSAGE }}"

            # Step 6: Commit and Push Results
            - name: Commit and Push Results
              run: |
                git config --local user.name "GitHub Actions"
                git config --local user.email "actions@github.com"
                mkdir -p output
                git add output
                git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
                git push origin HEAD:${{ github.ref }}
